using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.SceneInspector.Runtime")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.SceneInspector.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.DebugHost.Runtime")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.DebugHost.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.Commands.Runtime")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.Commands.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.Logging.Runtime")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.Logging.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.MiniTools.Runtime")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.MiniTools.Editor")]
[assembly: InternalsVisibleTo("DevUtilities.RemoteDevUtilities.MiniTools.EditorTests")]
[assembly: InternalsVisibleTo("DevUtilities.RuntimeSceneInspector.EditorTests")]
